# Generated by Django 4.0.3 on 2022-03-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_product',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=13990),
        ),
        migrations.AlterField(
            model_name='product',
            name='selled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='heigh',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='lenght',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='pac_heigh',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='pac_lenght',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='pac_width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stock_product',
            name='min_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type_product',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='type_product',
            name='material',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
