# Generated by Django 4.0.3 on 2022-03-16 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_product_imageproduct_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color_product',
            new_name='ColorProduct',
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.imageproduct'),
        ),
    ]
