# Generated by Django 4.0.3 on 2022-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_color_product_colorproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
