# Generated by Django 4.0.3 on 2022-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_sizeproduct_heigh_alter_sizeproduct_lenght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='type_product',
        ),
        migrations.AlterField(
            model_name='sizeproduct',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
