# Generated by Django 4.0.3 on 2022-03-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_stockproduct_type_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.imageproduct'),
        ),
    ]
