# Generated by Django 4.0.3 on 2022-03-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_tag_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.imageproduct'),
        ),
    ]
