# Generated by Django 4.0.3 on 2022-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productstock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockproduct',
            name='model',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
