# Generated by Django 4.0.3 on 2022-03-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_imageproduct_description_stockproduct_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='model',
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='productstock',
            name='model',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
