# Generated by Django 4.0.3 on 2022-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_stockproduct_model_imageproduct_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
