# Generated by Django 4.0.3 on 2022-03-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productstock_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproduct',
            old_name='url',
            new_name='img',
        ),
    ]
