# Generated by Django 4.0.3 on 2022-03-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_imageproduct_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageproduct',
            old_name='img',
            new_name='imgProduct',
        ),
    ]
